CREATE TABLE blog_posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(100),
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


