CREATE TABLE blog_posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(100),
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE blog_posts
ADD COLUMN image VARCHAR(255),
ADD COLUMN author VARCHAR(100);





